/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.miage.gi;

import com.miage.cards.*;
import com.miage.game.*;
import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Richard
 */
public class MapPanel extends javax.swing.JPanel {

    private Board b;
    private Player p1;
    private Deck d;
    private ArrayList<Card> ar;

    /**
     * Creates new form MapPanel
     */
    public MapPanel() throws IOException {
        initComponents();
        menuCardsPlayer.setVisible(false);
        closeMenuLabel.setVisible(false);
        displayedCardPanel.setVisible(false);
        menuCardsPlayer.remove(3);
        menuCardsPlayer.remove(2);
        b = new Board(2);
        p1 = new Player("Rouch");
        d = b.getDeck();
        ar = new ArrayList<Card>();
        ar.add(new CongressCard(8, "paris", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new CongressCard(10, "vienna", 2));
        ar.add(new SpecificKnowledgeCard(43, "london", 2, 2, "greece"));
        ar.add(new CongressCard(7, "london", 2));
        ar.add(new CarCard(5, "moscow", 2));
        p1.setCards(ar);
        menuCardsPlayer.setTitleAt(0, p1.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openMenuLabel = new javax.swing.JLabel();
        closeMenuLabel = new javax.swing.JLabel();
        menuCardsPlayer = new javax.swing.JTabbedPane();
        player1Panel = new javax.swing.JPanel();
        berlinAssistantP1Label = new javax.swing.JLabel();
        moscowCarP1Label = new javax.swing.JLabel();
        berlinEtnoP1Label = new javax.swing.JLabel();
        romaZeppelinP1Label = new javax.swing.JLabel();
        londonExcavationP1Label = new javax.swing.JLabel();
        berlinCongressP1Label = new javax.swing.JLabel();
        berlinGenKnowledgeP1Label = new javax.swing.JLabel();
        moscowScienKnowledgeP1Label = new javax.swing.JLabel();
        londonShovelP1Label = new javax.swing.JLabel();
        berlinSmallExpoP1Label = new javax.swing.JLabel();
        mesopotamiaExcavationP1Label = new javax.swing.JLabel();
        palestineExcavationP1Label = new javax.swing.JLabel();
        egyptExcavationP1Label = new javax.swing.JLabel();
        creteExcavationP1Label = new javax.swing.JLabel();
        greeceExcavationP1Label = new javax.swing.JLabel();
        mesopotamiaNullTokenP1Label = new javax.swing.JLabel();
        palestineNullTokenP1Label = new javax.swing.JLabel();
        greeceNullTokenP1Label = new javax.swing.JLabel();
        creteNullTokenP1Label = new javax.swing.JLabel();
        egyptNullTokenP1Label = new javax.swing.JLabel();
        player1BackgroundLabel = new javax.swing.JLabel();
        player2Panel = new javax.swing.JPanel();
        palestineExcavationP2Label = new javax.swing.JLabel();
        berlinEtnoP2Label = new javax.swing.JLabel();
        berlinGenKnowledgeP2Label = new javax.swing.JLabel();
        berlinCongressP2Label = new javax.swing.JLabel();
        berlinAssistantP2Label = new javax.swing.JLabel();
        romaZeppelinP2Label = new javax.swing.JLabel();
        moscowScienKnowledgeP2Label = new javax.swing.JLabel();
        mesopotamiaNullTokenP2Label = new javax.swing.JLabel();
        mesopotamiaExcavationP2Label = new javax.swing.JLabel();
        creteExcavationP2Label = new javax.swing.JLabel();
        berlinSmallExpoP2Label = new javax.swing.JLabel();
        greeceExcavationP2Label = new javax.swing.JLabel();
        moscowCarP2Label = new javax.swing.JLabel();
        londonExcavationP2Label = new javax.swing.JLabel();
        londonShovelP2Label = new javax.swing.JLabel();
        egyptExcavationP2Label = new javax.swing.JLabel();
        greeceNullTokenP2Label = new javax.swing.JLabel();
        palestineNullTokenP2Label = new javax.swing.JLabel();
        creteNullTokenP2Label = new javax.swing.JLabel();
        egyptNullTokenP2Label = new javax.swing.JLabel();
        player2BackgroundLabel = new javax.swing.JLabel();
        player3Panel = new javax.swing.JPanel();
        palestineExcavationP3Label = new javax.swing.JLabel();
        berlinEtnoP3Label = new javax.swing.JLabel();
        berlinGenKnowledgeP3Label = new javax.swing.JLabel();
        berlinCongressP3Label = new javax.swing.JLabel();
        berlinAssistantP3Label = new javax.swing.JLabel();
        romaZeppelinP3Label = new javax.swing.JLabel();
        moscowScienKnowledgeP3Label = new javax.swing.JLabel();
        mesopotamiaNullTokenP3Label = new javax.swing.JLabel();
        mesopotamiaExcavationP3Label = new javax.swing.JLabel();
        creteExcavationP3Label = new javax.swing.JLabel();
        berlinSmallExpoP3Label = new javax.swing.JLabel();
        greeceExcavationP3Label = new javax.swing.JLabel();
        moscowCarP3Label = new javax.swing.JLabel();
        londonExcavationP3Label = new javax.swing.JLabel();
        londonShovelP3Label = new javax.swing.JLabel();
        egyptExcavationP3Label = new javax.swing.JLabel();
        greeceNullTokenP3Label = new javax.swing.JLabel();
        palestineNullTokenP3Label = new javax.swing.JLabel();
        creteNullTokenP3Label = new javax.swing.JLabel();
        egyptNullTokenP3Label = new javax.swing.JLabel();
        player3BackgroundLabel = new javax.swing.JLabel();
        player4Panel = new javax.swing.JPanel();
        palestineExcavationP4Label = new javax.swing.JLabel();
        berlinEtnoP4Label = new javax.swing.JLabel();
        berlinGenKnowledgeP4Label = new javax.swing.JLabel();
        berlinCongressP4Label = new javax.swing.JLabel();
        berlinAssistantP4Label = new javax.swing.JLabel();
        romaZeppelinP4Label = new javax.swing.JLabel();
        moscowScienKnowledgeP4Label = new javax.swing.JLabel();
        mesopotamiaNullTokenP4Label = new javax.swing.JLabel();
        mesopotamiaExcavationP4Label = new javax.swing.JLabel();
        creteExcavationP4Label = new javax.swing.JLabel();
        berlinSmallExpoP4Label = new javax.swing.JLabel();
        greeceExcavationP4Label = new javax.swing.JLabel();
        moscowCarP4Label = new javax.swing.JLabel();
        londonExcavationP4Label = new javax.swing.JLabel();
        londonShovelP4Label = new javax.swing.JLabel();
        egyptExcavationP4Label = new javax.swing.JLabel();
        greeceNullTokenP4Label = new javax.swing.JLabel();
        palestineNullTokenP4Label = new javax.swing.JLabel();
        creteNullTokenP4Label = new javax.swing.JLabel();
        egyptNullTokenP4Label = new javax.swing.JLabel();
        player4BackgroundLabel = new javax.swing.JLabel();
        logMenu = new javax.swing.JPanel();
        logMenuScrollBar = new javax.swing.JScrollBar();
        usableCardsMenu = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        usedCardsMenu = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        displayedCardPanel = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/arrowRight.png"))); // NOI18N
        openMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openMenuLabelMouseClicked(evt);
            }
        });
        add(openMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        closeMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/arrowLeft.png"))); // NOI18N
        closeMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMenuLabelMouseClicked(evt);
            }
        });
        add(closeMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));
        closeMenuLabel.getAccessibleContext().setAccessibleName("closeMenuLabel");

        player1Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        berlinAssistantP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/18.jpg"))); // NOI18N
        player1Panel.add(berlinAssistantP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        moscowCarP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/5.jpg"))); // NOI18N
        moscowCarP1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moscowCarP1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moscowCarP1LabelMouseExited(evt);
            }
        });
        player1Panel.add(moscowCarP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        berlinEtnoP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/85.jpg"))); // NOI18N
        player1Panel.add(berlinEtnoP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        romaZeppelinP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/3.jpg"))); // NOI18N
        romaZeppelinP1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                romaZeppelinP1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                romaZeppelinP1LabelMouseExited(evt);
            }
        });
        player1Panel.add(romaZeppelinP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        londonExcavationP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/1.jpg"))); // NOI18N
        londonExcavationP1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                londonExcavationP1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                londonExcavationP1LabelMouseExited(evt);
            }
        });
        player1Panel.add(londonExcavationP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        berlinCongressP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/9.jpg"))); // NOI18N
        berlinCongressP1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berlinCongressP1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berlinCongressP1LabelMouseExited(evt);
            }
        });
        player1Panel.add(berlinCongressP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        berlinGenKnowledgeP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/31.jpg"))); // NOI18N
        berlinGenKnowledgeP1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berlinGenKnowledgeP1LabelMouseEntered(evt);
            }
        });
        player1Panel.add(berlinGenKnowledgeP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        moscowScienKnowledgeP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/74.jpg"))); // NOI18N
        player1Panel.add(moscowScienKnowledgeP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        londonShovelP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/22.jpg"))); // NOI18N
        player1Panel.add(londonShovelP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        berlinSmallExpoP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/88.jpg"))); // NOI18N
        player1Panel.add(berlinSmallExpoP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        mesopotamiaExcavationP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/mesopotamiaExcavation.jpg"))); // NOI18N
        player1Panel.add(mesopotamiaExcavationP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        palestineExcavationP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/palestineExcavation.jpg"))); // NOI18N
        player1Panel.add(palestineExcavationP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        egyptExcavationP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/egyptExcavation.jpg"))); // NOI18N
        player1Panel.add(egyptExcavationP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        creteExcavationP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/creteExcavation.jpg"))); // NOI18N
        player1Panel.add(creteExcavationP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        greeceExcavationP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/greeceExcavation.jpg"))); // NOI18N
        player1Panel.add(greeceExcavationP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        mesopotamiaNullTokenP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/mesopotamia/blueNull.png"))); // NOI18N
        player1Panel.add(mesopotamiaNullTokenP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, -1, -1));

        palestineNullTokenP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/palestine/greenNull.png"))); // NOI18N
        player1Panel.add(palestineNullTokenP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, -1, -1));

        greeceNullTokenP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/greece/orangeNull.png"))); // NOI18N
        player1Panel.add(greeceNullTokenP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, -1, -1));

        creteNullTokenP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/crete/purpleNull.png"))); // NOI18N
        player1Panel.add(creteNullTokenP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        egyptNullTokenP1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/egypt/yellowNull.png"))); // NOI18N
        player1Panel.add(egyptNullTokenP1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, -1, -1));

        player1BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/playerBackground.jpg"))); // NOI18N
        player1Panel.add(player1BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuCardsPlayer.addTab("Joueur 1", player1Panel);

        player2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        palestineExcavationP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/palestineExcavation.jpg"))); // NOI18N
        player2Panel.add(palestineExcavationP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        berlinEtnoP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/85.jpg"))); // NOI18N
        player2Panel.add(berlinEtnoP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        berlinGenKnowledgeP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/31.jpg"))); // NOI18N
        player2Panel.add(berlinGenKnowledgeP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        berlinCongressP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/9.jpg"))); // NOI18N
        player2Panel.add(berlinCongressP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        berlinAssistantP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/18.jpg"))); // NOI18N
        player2Panel.add(berlinAssistantP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        romaZeppelinP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/3.jpg"))); // NOI18N
        player2Panel.add(romaZeppelinP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        moscowScienKnowledgeP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/74.jpg"))); // NOI18N
        player2Panel.add(moscowScienKnowledgeP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        mesopotamiaNullTokenP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/mesopotamia/blueNull.png"))); // NOI18N
        player2Panel.add(mesopotamiaNullTokenP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, -1, -1));

        mesopotamiaExcavationP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/mesopotamiaExcavation.jpg"))); // NOI18N
        player2Panel.add(mesopotamiaExcavationP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        creteExcavationP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/creteExcavation.jpg"))); // NOI18N
        player2Panel.add(creteExcavationP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        berlinSmallExpoP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/88.jpg"))); // NOI18N
        player2Panel.add(berlinSmallExpoP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        greeceExcavationP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/greeceExcavation.jpg"))); // NOI18N
        player2Panel.add(greeceExcavationP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        moscowCarP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/5.jpg"))); // NOI18N
        player2Panel.add(moscowCarP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        londonExcavationP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/1.jpg"))); // NOI18N
        player2Panel.add(londonExcavationP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        londonShovelP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/22.jpg"))); // NOI18N
        player2Panel.add(londonShovelP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        egyptExcavationP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/egyptExcavation.jpg"))); // NOI18N
        player2Panel.add(egyptExcavationP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        greeceNullTokenP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/greece/orangeNull.png"))); // NOI18N
        player2Panel.add(greeceNullTokenP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, -1, -1));

        palestineNullTokenP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/palestine/greenNull.png"))); // NOI18N
        player2Panel.add(palestineNullTokenP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, -1, -1));

        creteNullTokenP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/crete/purpleNull.png"))); // NOI18N
        player2Panel.add(creteNullTokenP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        egyptNullTokenP2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/egypt/yellowNull.png"))); // NOI18N
        player2Panel.add(egyptNullTokenP2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, -1, -1));

        player2BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/playerBackground.jpg"))); // NOI18N
        player2Panel.add(player2BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuCardsPlayer.addTab("Joueur 2", player2Panel);

        player3Panel.setOpaque(false);
        player3Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        palestineExcavationP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/palestineExcavation.jpg"))); // NOI18N
        player3Panel.add(palestineExcavationP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        berlinEtnoP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/85.jpg"))); // NOI18N
        berlinEtnoP3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berlinEtnoP3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berlinEtnoP3LabelMouseExited(evt);
            }
        });
        player3Panel.add(berlinEtnoP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        berlinGenKnowledgeP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/31.jpg"))); // NOI18N
        berlinGenKnowledgeP3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berlinGenKnowledgeP3LabelMouseExited(evt);
            }
        });
        player3Panel.add(berlinGenKnowledgeP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        berlinCongressP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/9.jpg"))); // NOI18N
        player3Panel.add(berlinCongressP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        berlinAssistantP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/18.jpg"))); // NOI18N
        berlinAssistantP3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berlinAssistantP3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berlinAssistantP3LabelMouseExited(evt);
            }
        });
        player3Panel.add(berlinAssistantP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        romaZeppelinP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/3.jpg"))); // NOI18N
        player3Panel.add(romaZeppelinP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        moscowScienKnowledgeP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/74.jpg"))); // NOI18N
        moscowScienKnowledgeP3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moscowScienKnowledgeP3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moscowScienKnowledgeP3LabelMouseExited(evt);
            }
        });
        player3Panel.add(moscowScienKnowledgeP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        mesopotamiaNullTokenP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/mesopotamia/blueNull.png"))); // NOI18N
        player3Panel.add(mesopotamiaNullTokenP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, -1, -1));

        mesopotamiaExcavationP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/mesopotamiaExcavation.jpg"))); // NOI18N
        player3Panel.add(mesopotamiaExcavationP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        creteExcavationP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/creteExcavation.jpg"))); // NOI18N
        player3Panel.add(creteExcavationP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        berlinSmallExpoP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/88.jpg"))); // NOI18N
        berlinSmallExpoP3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                berlinSmallExpoP3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                berlinSmallExpoP3LabelMouseExited(evt);
            }
        });
        player3Panel.add(berlinSmallExpoP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        greeceExcavationP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/greeceExcavation.jpg"))); // NOI18N
        player3Panel.add(greeceExcavationP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        moscowCarP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/5.jpg"))); // NOI18N
        player3Panel.add(moscowCarP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        londonExcavationP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/1.jpg"))); // NOI18N
        player3Panel.add(londonExcavationP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        londonShovelP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/22.jpg"))); // NOI18N
        londonShovelP3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                londonShovelP3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                londonShovelP3LabelMouseExited(evt);
            }
        });
        player3Panel.add(londonShovelP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        egyptExcavationP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/egyptExcavation.jpg"))); // NOI18N
        player3Panel.add(egyptExcavationP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        greeceNullTokenP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/greece/orangeNull.png"))); // NOI18N
        player3Panel.add(greeceNullTokenP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, -1, -1));

        palestineNullTokenP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/palestine/greenNull.png"))); // NOI18N
        player3Panel.add(palestineNullTokenP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, -1, -1));

        creteNullTokenP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/crete/purpleNull.png"))); // NOI18N
        player3Panel.add(creteNullTokenP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        egyptNullTokenP3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/egypt/yellowNull.png"))); // NOI18N
        player3Panel.add(egyptNullTokenP3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, -1, -1));

        player3BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/playerBackground.jpg"))); // NOI18N
        player3Panel.add(player3BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuCardsPlayer.addTab("Joueur 3", player3Panel);

        player4Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        palestineExcavationP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/palestineExcavation.jpg"))); // NOI18N
        player4Panel.add(palestineExcavationP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, -1, -1));

        berlinEtnoP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/85.jpg"))); // NOI18N
        player4Panel.add(berlinEtnoP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        berlinGenKnowledgeP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/31.jpg"))); // NOI18N
        player4Panel.add(berlinGenKnowledgeP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        berlinCongressP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/9.jpg"))); // NOI18N
        player4Panel.add(berlinCongressP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        berlinAssistantP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/18.jpg"))); // NOI18N
        player4Panel.add(berlinAssistantP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        romaZeppelinP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/3.jpg"))); // NOI18N
        player4Panel.add(romaZeppelinP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        moscowScienKnowledgeP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/74.jpg"))); // NOI18N
        player4Panel.add(moscowScienKnowledgeP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        mesopotamiaNullTokenP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/mesopotamia/blueNull.png"))); // NOI18N
        player4Panel.add(mesopotamiaNullTokenP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, -1, -1));

        mesopotamiaExcavationP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/mesopotamiaExcavation.jpg"))); // NOI18N
        player4Panel.add(mesopotamiaExcavationP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, -1, -1));

        creteExcavationP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/creteExcavation.jpg"))); // NOI18N
        player4Panel.add(creteExcavationP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        berlinSmallExpoP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/88.jpg"))); // NOI18N
        player4Panel.add(berlinSmallExpoP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        greeceExcavationP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/greeceExcavation.jpg"))); // NOI18N
        player4Panel.add(greeceExcavationP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        moscowCarP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/5.jpg"))); // NOI18N
        player4Panel.add(moscowCarP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        londonExcavationP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/1.jpg"))); // NOI18N
        player4Panel.add(londonExcavationP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        londonShovelP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/22.jpg"))); // NOI18N
        player4Panel.add(londonShovelP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        egyptExcavationP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/excavations/recto/egyptExcavation.jpg"))); // NOI18N
        player4Panel.add(egyptExcavationP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        greeceNullTokenP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/greece/orangeNull.png"))); // NOI18N
        player4Panel.add(greeceNullTokenP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, -1, -1));

        palestineNullTokenP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/palestine/greenNull.png"))); // NOI18N
        player4Panel.add(palestineNullTokenP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, -1, -1));

        creteNullTokenP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/crete/purpleNull.png"))); // NOI18N
        player4Panel.add(creteNullTokenP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        egyptNullTokenP4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tokens/egypt/yellowNull.png"))); // NOI18N
        player4Panel.add(egyptNullTokenP4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 650, -1, -1));

        player4BackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/playerBackground.jpg"))); // NOI18N
        player4Panel.add(player4BackgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuCardsPlayer.addTab("Joueur 4", player4Panel);

        add(menuCardsPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 770));

        logMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        logMenu.add(logMenuScrollBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 180));

        add(logMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 320, 180));

        usableCardsMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        usableCardsMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 10));

        add(usableCardsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 180, 320, 370));

        usedCardsMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        usedCardsMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, -1));

        add(usedCardsMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 550, 320, 220));

        displayedCardPanel.setOpaque(false);
        add(displayedCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 550, 730));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/map.jpg"))); // NOI18N
        add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openMenuLabelMouseClicked
        openMenuLabel.setVisible(false);
        menuCardsPlayer.setVisible(true);
        closeMenuLabel.setVisible(true);
        backgroundLabel.setEnabled(false);
        logMenu.setEnabled(false);
        usedCardsMenu.setEnabled(false);
        usableCardsMenu.setEnabled(false);
    }//GEN-LAST:event_openMenuLabelMouseClicked

    private void closeMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMenuLabelMouseClicked
        openMenuLabel.setVisible(true);
        menuCardsPlayer.setVisible(false);
        closeMenuLabel.setVisible(false);
        backgroundLabel.setEnabled(true);
        logMenu.setEnabled(true);
        usedCardsMenu.setEnabled(true);
        usableCardsMenu.setEnabled(true);
    }//GEN-LAST:event_closeMenuLabelMouseClicked

    private void berlinCongressP1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinCongressP1LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof CongressCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_berlinCongressP1LabelMouseEntered

    private void berlinCongressP1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinCongressP1LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_berlinCongressP1LabelMouseExited

    private void moscowCarP1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moscowCarP1LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof CarCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_moscowCarP1LabelMouseEntered

    private void moscowCarP1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moscowCarP1LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_moscowCarP1LabelMouseExited

    private void londonExcavationP1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_londonExcavationP1LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof ExcavationAuthorizationCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_londonExcavationP1LabelMouseEntered

    private void londonExcavationP1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_londonExcavationP1LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_londonExcavationP1LabelMouseExited

    private void romaZeppelinP1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romaZeppelinP1LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof ZeppelinCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_romaZeppelinP1LabelMouseEntered

    private void romaZeppelinP1LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_romaZeppelinP1LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_romaZeppelinP1LabelMouseExited

    private void berlinGenKnowledgeP1LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinGenKnowledgeP1LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof GeneralKnowledgeCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_berlinGenKnowledgeP1LabelMouseEntered

    private void berlinGenKnowledgeP3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinGenKnowledgeP3LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_berlinGenKnowledgeP3LabelMouseExited

    private void berlinEtnoP3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinEtnoP3LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof EthnologicalKnowledgeCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_berlinEtnoP3LabelMouseEntered

    private void berlinEtnoP3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinEtnoP3LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_berlinEtnoP3LabelMouseExited

    private void londonShovelP3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_londonShovelP3LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof ShovelCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_londonShovelP3LabelMouseEntered

    private void londonShovelP3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_londonShovelP3LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_londonShovelP3LabelMouseExited

    private void berlinAssistantP3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinAssistantP3LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof AssistantCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_berlinAssistantP3LabelMouseEntered

    private void berlinAssistantP3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinAssistantP3LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_berlinAssistantP3LabelMouseExited

    private void moscowScienKnowledgeP3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moscowScienKnowledgeP3LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof SpecificKnowledgeCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_moscowScienKnowledgeP3LabelMouseEntered

    private void moscowScienKnowledgeP3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moscowScienKnowledgeP3LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_moscowScienKnowledgeP3LabelMouseExited

    private void berlinSmallExpoP3LabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinSmallExpoP3LabelMouseEntered
        displayedCardPanel.setVisible(true);
        for (Card c : p1.getCards()) {
            if (c instanceof ExpoCard) {
                javax.swing.JLabel k = new javax.swing.JLabel();
                k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cards/" + c.getId() + ".jpg")));
                displayedCardPanel.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
            }
        }
        usedCardsMenu.updateUI();
    }//GEN-LAST:event_berlinSmallExpoP3LabelMouseEntered

    private void berlinSmallExpoP3LabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berlinSmallExpoP3LabelMouseExited
        displayedCardPanel.setVisible(false);
        displayedCardPanel.removeAll();
    }//GEN-LAST:event_berlinSmallExpoP3LabelMouseExited
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel berlinAssistantP1Label;
    private javax.swing.JLabel berlinAssistantP2Label;
    private javax.swing.JLabel berlinAssistantP3Label;
    private javax.swing.JLabel berlinAssistantP4Label;
    private javax.swing.JLabel berlinCongressP1Label;
    private javax.swing.JLabel berlinCongressP2Label;
    private javax.swing.JLabel berlinCongressP3Label;
    private javax.swing.JLabel berlinCongressP4Label;
    private javax.swing.JLabel berlinEtnoP1Label;
    private javax.swing.JLabel berlinEtnoP2Label;
    private javax.swing.JLabel berlinEtnoP3Label;
    private javax.swing.JLabel berlinEtnoP4Label;
    private javax.swing.JLabel berlinGenKnowledgeP1Label;
    private javax.swing.JLabel berlinGenKnowledgeP2Label;
    private javax.swing.JLabel berlinGenKnowledgeP3Label;
    private javax.swing.JLabel berlinGenKnowledgeP4Label;
    private javax.swing.JLabel berlinSmallExpoP1Label;
    private javax.swing.JLabel berlinSmallExpoP2Label;
    private javax.swing.JLabel berlinSmallExpoP3Label;
    private javax.swing.JLabel berlinSmallExpoP4Label;
    private javax.swing.JLabel closeMenuLabel;
    private javax.swing.JLabel creteExcavationP1Label;
    private javax.swing.JLabel creteExcavationP2Label;
    private javax.swing.JLabel creteExcavationP3Label;
    private javax.swing.JLabel creteExcavationP4Label;
    private javax.swing.JLabel creteNullTokenP1Label;
    private javax.swing.JLabel creteNullTokenP2Label;
    private javax.swing.JLabel creteNullTokenP3Label;
    private javax.swing.JLabel creteNullTokenP4Label;
    private javax.swing.JPanel displayedCardPanel;
    private javax.swing.JLabel egyptExcavationP1Label;
    private javax.swing.JLabel egyptExcavationP2Label;
    private javax.swing.JLabel egyptExcavationP3Label;
    private javax.swing.JLabel egyptExcavationP4Label;
    private javax.swing.JLabel egyptNullTokenP1Label;
    private javax.swing.JLabel egyptNullTokenP2Label;
    private javax.swing.JLabel egyptNullTokenP3Label;
    private javax.swing.JLabel egyptNullTokenP4Label;
    private javax.swing.JLabel greeceExcavationP1Label;
    private javax.swing.JLabel greeceExcavationP2Label;
    private javax.swing.JLabel greeceExcavationP3Label;
    private javax.swing.JLabel greeceExcavationP4Label;
    private javax.swing.JLabel greeceNullTokenP1Label;
    private javax.swing.JLabel greeceNullTokenP2Label;
    private javax.swing.JLabel greeceNullTokenP3Label;
    private javax.swing.JLabel greeceNullTokenP4Label;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel logMenu;
    private javax.swing.JScrollBar logMenuScrollBar;
    private javax.swing.JLabel londonExcavationP1Label;
    private javax.swing.JLabel londonExcavationP2Label;
    private javax.swing.JLabel londonExcavationP3Label;
    private javax.swing.JLabel londonExcavationP4Label;
    private javax.swing.JLabel londonShovelP1Label;
    private javax.swing.JLabel londonShovelP2Label;
    private javax.swing.JLabel londonShovelP3Label;
    private javax.swing.JLabel londonShovelP4Label;
    private javax.swing.JTabbedPane menuCardsPlayer;
    private javax.swing.JLabel mesopotamiaExcavationP1Label;
    private javax.swing.JLabel mesopotamiaExcavationP2Label;
    private javax.swing.JLabel mesopotamiaExcavationP3Label;
    private javax.swing.JLabel mesopotamiaExcavationP4Label;
    private javax.swing.JLabel mesopotamiaNullTokenP1Label;
    private javax.swing.JLabel mesopotamiaNullTokenP2Label;
    private javax.swing.JLabel mesopotamiaNullTokenP3Label;
    private javax.swing.JLabel mesopotamiaNullTokenP4Label;
    private javax.swing.JLabel moscowCarP1Label;
    private javax.swing.JLabel moscowCarP2Label;
    private javax.swing.JLabel moscowCarP3Label;
    private javax.swing.JLabel moscowCarP4Label;
    private javax.swing.JLabel moscowScienKnowledgeP1Label;
    private javax.swing.JLabel moscowScienKnowledgeP2Label;
    private javax.swing.JLabel moscowScienKnowledgeP3Label;
    private javax.swing.JLabel moscowScienKnowledgeP4Label;
    private javax.swing.JLabel openMenuLabel;
    private javax.swing.JLabel palestineExcavationP1Label;
    private javax.swing.JLabel palestineExcavationP2Label;
    private javax.swing.JLabel palestineExcavationP3Label;
    private javax.swing.JLabel palestineExcavationP4Label;
    private javax.swing.JLabel palestineNullTokenP1Label;
    private javax.swing.JLabel palestineNullTokenP2Label;
    private javax.swing.JLabel palestineNullTokenP3Label;
    private javax.swing.JLabel palestineNullTokenP4Label;
    private javax.swing.JLabel player1BackgroundLabel;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JLabel player2BackgroundLabel;
    private javax.swing.JPanel player2Panel;
    private javax.swing.JLabel player3BackgroundLabel;
    private javax.swing.JPanel player3Panel;
    private javax.swing.JLabel player4BackgroundLabel;
    private javax.swing.JPanel player4Panel;
    private javax.swing.JLabel romaZeppelinP1Label;
    private javax.swing.JLabel romaZeppelinP2Label;
    private javax.swing.JLabel romaZeppelinP3Label;
    private javax.swing.JLabel romaZeppelinP4Label;
    private javax.swing.JPanel usableCardsMenu;
    private javax.swing.JPanel usedCardsMenu;
    // End of variables declaration//GEN-END:variables
}
